name: a3mcat
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - numpy<2
  - biopython>=1.80
  - importlib-resources
  - jupyterlab
  - pip:
    - python-dotenv
    - mkdocs
    - -e .
